using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace Aiursoft.DocsViewer.Entities;

[ExcludeFromCodeCoverage]
public class Document
{
    [Key]
    public int Id { get; set; }

    /// <summary>File name without extension, e.g. "getting-started"</summary>
    [MaxLength(200)]
    public required string Title { get; set; }

    /// <summary>Top-level folder name, e.g. "guide", or "root" for top-level files.</summary>
    [MaxLength(100)]
    public required string Category { get; set; }

    /// <summary>Repo-relative path, e.g. "guide/getting-started/install.md"</summary>
    [MaxLength(500)]
    public required string FilePath { get; set; }

    /// <summary>Full Markdown content of the file.</summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>Last-commit timestamp from git log.</summary>
    public DateTime FileLastModified { get; set; }

    /// <summary>Soft-delete flag.</summary>
    public bool IsDeleted { get; set; }

    /// <summary>1024-dimensional float32 vector generated by the embedding model for vector search.</summary>
    public byte[]? Embedding { get; set; }

    /// <summary>UTC timestamp of the last successful embedding generation.</summary>
    public DateTime LastEmbeddedAt { get; set; } = DateTime.MinValue;

    public ICollection<LocalizedDocument> LocalizedDocuments { get; set; } = [];
    public ICollection<DocumentComment> Comments { get; set; } = [];
    public ICollection<DocumentLike> Likes { get; set; } = [];
    public ICollection<DocumentFavorite> Favorites { get; set; } = [];
}
