using System.Text.RegularExpressions;
using Aiursoft.Scanner.Abstractions;
using Aiursoft.DocsViewer.Services.FileStorage;
using Ganss.Xss;
using Markdig;

namespace Aiursoft.DocsViewer.Services;

/// <summary>
/// Renders markdown to HTML, resolving StorageService logical image paths to public URLs.
/// </summary>
public partial class DocumentMarkdownRenderer(StorageService storageService, HtmlSanitizer sanitizer) : IScopedDependency
{
    /// <summary>
    /// Matches src attribute pointing to a logical workspace path (e.g. doc-images/abc123.png).
    /// </summary>
    [GeneratedRegex(@"src=""([^""]*doc-images/[^""]+)""", RegexOptions.Compiled)]
    private static partial Regex LogicalPathRegex();

    /// <summary>
    /// Matches img tags that lack a class attribute, to add Bootstrap's img-fluid.
    /// </summary>
    [GeneratedRegex(@"<img\s+(?![^>]*\bclass\s*=)", RegexOptions.Compiled)]
    private static partial Regex ImgWithoutClassRegex();

    public string RenderHtml(string markdown)
    {
        // Protect only the HTML generated by our MkDocs admonition preprocessor. User-authored
        // HTML remains in the Markdown input and is disabled by the pipeline below.
        var preprocessed = AdmonitionPreprocessor.PreprocessWithPlaceholders(markdown);

        var pipeline = new MarkdownPipelineBuilder()
            .UseAdvancedExtensions()
            .UseAutoLinks()
            .UsePipeTables()
            .UseGridTables()
            .DisableHtml()
            .Build();

        var html = Markdown.ToHtml(preprocessed.Markdown, pipeline);

        foreach (var replacement in preprocessed.HtmlReplacements)
        {
            html = html.Replace($"<p>{replacement.Key}</p>", replacement.Value, StringComparison.Ordinal);
        }

        // Replace logical storage paths with public URLs
        html = LogicalPathRegex().Replace(html, match =>
        {
            var logicalPath = match.Groups[1].Value;
            var url = storageService.RelativePathToInternetUrl(logicalPath, isVault: false);
            return $"src=\"{url}\"";
        });

        // Add Bootstrap img-fluid class to all images for responsive sizing
        html = ImgWithoutClassRegex().Replace(html, "<img class=\"img-fluid\" ");

        // Sanitize after all transformations
        html = sanitizer.Sanitize(html);

        return html;
    }
}
